nyc_taxi:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PW') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: nyc_taxi
      threads: 1
